version: 0.2

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      java: corretto11
    commands:
      - echo install
  pre_build:
    on-failure: ABORT
    commands:
      - echo pre_build
  build:
    on-failure: ABORT
    commands:
      - mvn package
      - echo build
  post_build:
    on-failure: ABORT
    commands:
      - echo post_build
artifacts:
  files:
    - "**/*"
    - target/02-spring-boot-todo-rest-api-h2-continuous-deployment-pipeline-0.0.1-SNAPSHOT.jar
  discard-paths: yes
